/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package flox.gradle

class App {
    val greeting: String
        get() {
            return "Hello Kotlin World from flox!!"
        }
}

fun main() {
    println(App().greeting)
}
